import {
  type BusinessUnit,
  type Table,
  type Category,
  type MenuItem,
  type User,
  TableStatus,
  ItemType,
} from "@/types/schema"

// Mock Business Unit
export const mockBusinessUnit: BusinessUnit = {
  id: "bu-001",
  code: "REST001",
  name: "Bella Vista Restaurant",
  address: "123 Main Street, Downtown",
  phone: "+1-555-0123",
  email: "info@bellavista.com",
  timezone: "Asia/Manila",
  currency: "PHP",
  taxRate: 0.12,
  isActive: true,
  settings: {},
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
}

// Mock Tables
export const mockTables: Table[] = [
  {
    id: "table-001",
    businessUnitId: "bu-001",
    number: 1,
    capacity: 2,
    status: TableStatus.AVAILABLE,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-002",
    businessUnitId: "bu-001",
    number: 2,
    capacity: 4,
    status: TableStatus.OCCUPIED,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-003",
    businessUnitId: "bu-001",
    number: 3,
    capacity: 6,
    status: TableStatus.AVAILABLE,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-004",
    businessUnitId: "bu-001",
    number: 4,
    capacity: 2,
    status: TableStatus.RESERVED,
    location: "Patio",
    isActive: true,
  },
  {
    id: "table-005",
    businessUnitId: "bu-001",
    number: 5,
    capacity: 8,
    status: TableStatus.AVAILABLE,
    location: "Private Room",
    isActive: true,
  },
   {
    id: "table-006",
    businessUnitId: "bu-001",
    number: 6,
    capacity: 2,
    status: TableStatus.AVAILABLE,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-007",
    businessUnitId: "bu-001",
    number: 7,
    capacity: 4,
    status: TableStatus.OCCUPIED,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-008",
    businessUnitId: "bu-001",
    number: 8,
    capacity: 6,
    status: TableStatus.AVAILABLE,
    location: "Main Floor",
    isActive: true,
  },
  {
    id: "table-009",
    businessUnitId: "bu-001",
    number: 9,
    capacity: 2,
    status: TableStatus.RESERVED,
    location: "Patio",
    isActive: true,
  },
  {
    id: "table-010",
    businessUnitId: "bu-001",
    number: 10,
    capacity: 8,
    status: TableStatus.AVAILABLE,
    location: "Private Room",
    isActive: true,
  },
]

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: "cat-002",
    businessUnitId: "bu-001",
    name: "Food",
    description: "Main dishes and appetizers",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-003",
    businessUnitId: "bu-001",
    name: "Drinks",
    description: "Beverages and cocktails",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-004",
    businessUnitId: "bu-001",
    name: "Desserts",
    description: "Sweet treats and desserts",
    sortOrder: 3,
    isActive: true,
  },
]

// Mock Menu Items
export const mockMenuItems: MenuItem[] = [
  // Food Items
  {
    id: "item-001",
    businessUnitId: "bu-001",
    name: "Cheeseburger",
    description: "Juicy beef patty with cheese, lettuce, tomato",
    price: 450.0,
    categoryId: "cat-002",
    type: ItemType.FOOD,
    prepTime: 15,
    isAvailable: true,
    imageUrl: "/classic-cheeseburger.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-002",
    businessUnitId: "bu-001",
    name: "Pepperoni Pizza",
    description: "Classic pizza with pepperoni and mozzarella",
    price: 650.0,
    categoryId: "cat-002",
    type: ItemType.FOOD,
    prepTime: 20,
    isAvailable: true,
    imageUrl: "/pepperoni-pizza.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-003",
    businessUnitId: "bu-001",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with caesar dressing",
    price: 400.0,
    categoryId: "cat-002",
    type: ItemType.FOOD,
    prepTime: 10,
    isAvailable: true,
    imageUrl: "/caesar-salad.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-004",
    businessUnitId: "bu-001",
    name: "Chicken Wings",
    description: "Spicy buffalo wings with ranch dip",
    price: 500.0,
    categoryId: "cat-002",
    type: ItemType.FOOD,
    prepTime: 18,
    isAvailable: true,
    imageUrl: "/crispy-chicken-wings.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-005",
    businessUnitId: "bu-001",
    name: "French Fries",
    description: "Crispy golden french fries",
    price: 200.0,
    categoryId: "cat-002",
    type: ItemType.FOOD,
    prepTime: 8,
    isAvailable: true,
    imageUrl: "/crispy-french-fries.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Drink Items
  {
    id: "item-006",
    businessUnitId: "bu-001",
    name: "Coca Cola",
    description: "Classic cola soft drink",
    price: 125.0,
    categoryId: "cat-003",
    type: ItemType.DRINK,
    prepTime: 2,
    isAvailable: true,
    imageUrl: "/refreshing-cola.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-007",
    businessUnitId: "bu-001",
    name: "Iced Tea",
    description: "Refreshing iced tea with lemon",
    price: 150.0,
    categoryId: "cat-003",
    type: ItemType.DRINK,
    prepTime: 3,
    isAvailable: true,
    imageUrl: "/iced-tea.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-008",
    businessUnitId: "bu-001",
    name: "Orange Juice",
    description: "Fresh squeezed orange juice",
    price: 175.0,
    categoryId: "cat-003",
    type: ItemType.DRINK,
    prepTime: 2,
    isAvailable: true,
    imageUrl: "/glass-of-orange-juice.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-009",
    businessUnitId: "bu-001",
    name: "Latte",
    description: "Espresso with steamed milk",
    price: 225.0,
    categoryId: "cat-003",
    type: ItemType.DRINK,
    prepTime: 5,
    isAvailable: true,
    imageUrl: "/latte-coffee.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-010",
    businessUnitId: "bu-001",
    name: "Bottled Water",
    description: "Pure spring water",
    price: 100.0,
    categoryId: "cat-003",
    type: ItemType.DRINK,
    prepTime: 1,
    isAvailable: true,
    imageUrl: "/bottled-water.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Dessert Items
  {
    id: "item-011",
    businessUnitId: "bu-001",
    name: "Chocolate Cake",
    description: "Rich chocolate layer cake",
    price: 300.0,
    categoryId: "cat-004",
    type: ItemType.FOOD,
    prepTime: 5,
    isAvailable: true,
    imageUrl: "/decadent-chocolate-cake.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "item-012",
    businessUnitId: "bu-001",
    name: "Ice Cream Sundae",
    description: "Vanilla ice cream with chocolate sauce",
    price: 250.0,
    categoryId: "cat-004",
    type: ItemType.FOOD,
    prepTime: 3,
    isAvailable: true,
    imageUrl: "/ice-cream-sundae.png",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Mock User (Waiter)
export const mockWaiter: User = {
  id: "user-001",
  email: "john.doe@bellavista.com",
  username: "johndoe",
  name: "John Doe",
  isActive: true,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
}
